<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Shelby Provost" />


<title>CaseStudy1</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">About Me</a>
</li>
<li>
  <a href="CaseStudy1.html">Beer Study</a>
</li>
<li>
  <a href="CaseStudy2.html">Attrition Study</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">CaseStudy1</h1>
<h4 class="author">Shelby Provost</h4>
<h4 class="date">6/24/2021</h4>

</div>


<p>Given the Beers data set, containing information of 2410 US craft beers, and the Breweries data set, containing 558 US breweries, an exploratory data analysis (EDA) was performed to extract potential insights from the data.</p>
<p>The first step of the analysis is to import and merge the breweries data with the beers data.</p>
<pre><code>##   Brewery_id        Name.x Beer_ID   ABV IBU                               Style Ounces             Name.y
## 1          1  Get Together    2692 0.045  50                        American IPA     16 NorthGate Brewing 
## 2          1 Maggie&#39;s Leap    2691 0.049  26                  Milk / Sweet Stout     16 NorthGate Brewing 
## 3          1    Wall&#39;s End    2690 0.048  19                   English Brown Ale     16 NorthGate Brewing 
## 4          1       Pumpion    2689 0.060  38                         Pumpkin Ale     16 NorthGate Brewing 
## 5          1    Stronghold    2688 0.060  25                     American Porter     16 NorthGate Brewing 
## 6          1   Parapet ESB    2687 0.056  47 Extra Special / Strong Bitter (ESB)     16 NorthGate Brewing 
##          City State
## 1 Minneapolis    MN
## 2 Minneapolis    MN
## 3 Minneapolis    MN
## 4 Minneapolis    MN
## 5 Minneapolis    MN
## 6 Minneapolis    MN</code></pre>
<pre><code>##      Brewery_id                    Name.x Beer_ID   ABV IBU                   Style Ounces
## 2405        556             Pilsner Ukiah      98 0.055  NA         German Pilsener     12
## 2406        557  Heinnieweisse Weissebier      52 0.049  NA              Hefeweizen     12
## 2407        557           Snapperhead IPA      51 0.068  NA            American IPA     12
## 2408        557         Moo Thunder Stout      50 0.049  NA      Milk / Sweet Stout     12
## 2409        557         Porkslap Pale Ale      49 0.043  NA American Pale Ale (APA)     12
## 2410        558 Urban Wilderness Pale Ale      30 0.049  NA        English Pale Ale     12
##                             Name.y          City State
## 2405         Ukiah Brewing Company         Ukiah    CA
## 2406       Butternuts Beer and Ale Garrattsville    NY
## 2407       Butternuts Beer and Ale Garrattsville    NY
## 2408       Butternuts Beer and Ale Garrattsville    NY
## 2409       Butternuts Beer and Ale Garrattsville    NY
## 2410 Sleeping Lady Brewing Company     Anchorage    AK</code></pre>
<p>Then a visual representation of the number of breweries in each state is created with a bar chart ordered from most to least number of breweries. The top 5 and bottom 5 states are extracted from the ordered data as well. <img src="CaseStudy1_files/figure-html/Number%20of%20Breweries%20Bar%20Chart-1.png" width="672" /></p>
<pre><code>## # A tibble: 5 x 2
##   State count
##   &lt;chr&gt; &lt;int&gt;
## 1 &quot; DC&quot;     1
## 2 &quot; ND&quot;     1
## 3 &quot; SD&quot;     1
## 4 &quot; WV&quot;     1
## 5 &quot; AR&quot;     2</code></pre>
<pre><code>## # A tibble: 5 x 2
##   State count
##   &lt;chr&gt; &lt;int&gt;
## 1 &quot; TX&quot;    28
## 2 &quot; OR&quot;    29
## 3 &quot; MI&quot;    32
## 4 &quot; CA&quot;    39
## 5 &quot; CO&quot;    47</code></pre>
<pre><code>## [1] 0.08422939</code></pre>
<p>The states with the most breweries are Colorado, California, Michigan, Oregon, and Texas. With 47 breweries, Colorado is home to 8.4% of the breweries. The states with the least breweries are District of Columbia, North Dakota, South Dakota, and West Virginia.</p>
<p>To perform additional analysis, the merged data is checked for NA’s.</p>
<pre><code>## [1] &quot;&quot;
## [1] &quot;&quot;
## [1] &quot;&quot;
## [1] &quot;Has NA&quot;
## [1] &quot;Has NA&quot;
## [1] &quot;&quot;
## [1] &quot;&quot;
## [1] &quot;&quot;
## [1] &quot;&quot;
## [1] &quot;&quot;</code></pre>
<pre><code>##            sapply.BeersAndBrews..function.x...
## Brewery_id                                    
## Name.x                                        
## Beer_ID                                       
## ABV                                     Has NA
## IBU                                     Has NA
## Style                                         
## Ounces                                        
## Name.y                                        
## City                                          
## State</code></pre>
<pre><code>##    Mode   FALSE    TRUE 
## logical    2348      62</code></pre>
<pre><code>##    Mode   FALSE    TRUE 
## logical    1405    1005</code></pre>
<p>The ABV variable has 62 NA values and the IBU variable has 1005 NA values. The NA’s will stay in the merged data set, however they will be filtered out when necessary throughout the analysis.</p>
<p>The median ABV and IBU by state are computed and visually represented with the NA values removed. <img src="CaseStudy1_files/figure-html/Medians%20for%20ABV%20and%20IBU-1.png" width="672" /></p>
<pre><code>##   Med_ABV_All
## 1       0.056</code></pre>
<p><img src="CaseStudy1_files/figure-html/Medians%20for%20ABV%20and%20IBU-2.png" width="672" /></p>
<pre><code>##   Med_IBU_All
## 1          35</code></pre>
<p>The states with the highest ABV and the highest IBU are extracted.</p>
<pre><code>## [1] &quot;State with the maximum alcoholic beer:  CO, Lee Hill Series Vol. 5 - Belgian Style Quadrupel Ale from Upslope Brewing Company, with an alcohol percentage of 12.8%&quot;</code></pre>
<pre><code>## [1] &quot;State with the maximum bitterness:  OR, Bitter Bitch Imperial IPA from Astoria Brewing Company with an IBU of 138&quot;</code></pre>
<p>The distribution of the alcoholic content is examined further. <img src="CaseStudy1_files/figure-html/ABV%20Distribution-1.png" width="672" /> The distribution of the alcoholic content appears to be slightly right skewed. There also is evidence of an outlier.</p>
<p>The distribution of the international bitterness is examined further. <img src="CaseStudy1_files/figure-html/IBU%20Distribution-1.png" width="672" /> The distribution of the international bitterness appears to be right skewed.</p>
<p>Then, ABV and IBU are assessed for a relationship. <img src="CaseStudy1_files/figure-html/Relationship-1.png" width="672" /></p>
<pre><code>## 
## Call:
## lm(formula = IBU ~ ABV, data = BeersAndBrews)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -78.849 -11.977  -0.721  13.997  93.458 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -34.099      2.326  -14.66   &lt;2e-16 ***
## ABV         1282.037     37.860   33.86   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 19.26 on 1403 degrees of freedom
##   (1005 observations deleted due to missingness)
## Multiple R-squared:  0.4497, Adjusted R-squared:  0.4493 
## F-statistic:  1147 on 1 and 1403 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>There is evidence of a linear relationship between ABV and IBU. This can be seen by the regression line showing a positive trend in the data.The higher the ABV, the larger the residuals appear to be, however this is not evidence against the trend since it is likely due to a smaller amount of data points in that range. A test was performed concluding that this visual relationship is significant. It provided a linear regression estimate of: IBU = -34.1 + 1282.037(ABV).</p>
<p>Style flags are used to prepare the data for machine learning.</p>
<pre><code>## 
##                                                        Abbey Single Ale                             Altbier 
##                                   5                                   2                                  13 
##              American Adjunct Lager            American Amber / Red Ale          American Amber / Red Lager 
##                                  18                                 133                                  29 
##                 American Barleywine                  American Black Ale                 American Blonde Ale 
##                                   3                                  36                                 108 
##                  American Brown Ale             American Dark Wheat Ale      American Double / Imperial IPA 
##                                  70                                   7                                 105 
##  American Double / Imperial Pilsner    American Double / Imperial Stout           American India Pale Lager 
##                                   2                                   9                                   3 
##                        American IPA                American Malt Liquor             American Pale Ale (APA) 
##                                 424                                   1                                 245 
##                 American Pale Lager             American Pale Wheat Ale                    American Pilsner 
##                                  39                                  97                                  25 
##                     American Porter                      American Stout                 American Strong Ale 
##                                  68                                  39                                  14 
##                  American White IPA                   American Wild Ale                       Baltic Porter 
##                                  11                                   6                                   6 
##                    Belgian Dark Ale                         Belgian IPA                    Belgian Pale Ale 
##                                  11                                  18                                  24 
##             Belgian Strong Dark Ale             Belgian Strong Pale Ale                  Berliner Weissbier 
##                                   6                                   7                                  11 
##                     BiÃ¨re de Garde                                Bock                             Braggot 
##                                   7                                   7                                   1 
##      California Common / Steam Beer                          Chile Beer                               Cider 
##                                   6                                   3                                  37 
##                           Cream Ale                      Czech Pilsener                          Doppelbock 
##                                  29                                  28                                   7 
##           Dortmunder / Export Lager                              Dubbel                        Dunkelweizen 
##                                   6                                   5                                   4 
##                  English Barleywine                      English Bitter                   English Brown Ale 
##                                   3                                   3                                  18 
##               English Dark Mild Ale        English India Pale Ale (IPA)                    English Pale Ale 
##                                   6                                  13                                  12 
##               English Pale Mild Ale                       English Stout                  English Strong Ale 
##                                   3                                   2                                   4 
##                     Euro Dark Lager                     Euro Pale Lager Extra Special / Strong Bitter (ESB) 
##                                   5                                   2                                  20 
##                  Flanders Oud Bruin                    Flanders Red Ale              Foreign / Export Stout 
##                                   1                                   1                                   6 
##              Fruit / Vegetable Beer                     German Pilsener                                Gose 
##                                  49                                  36                                  10 
##                            Grisette                          Hefeweizen                Herbed / Spiced Beer 
##                                   1                                  40                                   9 
##                     Irish Dry Stout                       Irish Red Ale                             KÃ¶lsch 
##                                   5                                  12                                  42 
##          Keller Bier / Zwickel Bier                       Kristalweizen                         Light Lager 
##                                   3                                   1                                  12 
##                    Low Alcohol Beer               MÃ¤rzen / Oktoberfest               Maibock / Helles Bock 
##                                   1                                  30                                   5 
##                                Mead                  Milk / Sweet Stout                 Munich Dunkel Lager 
##                                   5                                  10                                   4 
##                 Munich Helles Lager                       Oatmeal Stout                             Old Ale 
##                                  20                                  18                                   2 
##                               Other                         Pumpkin Ale                    Quadrupel (Quad) 
##                                   1                                  23                                   4 
##                              Radler                           Rauchbier                          Roggenbier 
##                                   3                                   2                                   2 
##              Russian Imperial Stout                            Rye Beer              Saison / Farmhouse Ale 
##                                  11                                  18                                  52 
##                         Schwarzbier              Scotch Ale / Wee Heavy                        Scottish Ale 
##                                   9                                  15                                  19 
##                              Shandy                         Smoked Beer                              Tripel 
##                                   3                                   1                                  11 
##                        Vienna Lager                           Wheat Ale                       Winter Warmer 
##                                  20                                   1                                  15 
##                             Witbier 
##                                  51</code></pre>
<p>KNN classification is used to investigate the relationship of ABV and IBU between India Pale Ales (IPA) and all other types of Ales.</p>
<p>The training data set contains 80% of the data, while the test data set contains the remaining 20%.</p>
<p>KNN classifications of IPA’s <img src="CaseStudy1_files/figure-html/KNN%20IPA-1.png" width="672" /></p>
<pre><code>## [1] &quot;Confusion Matrix of Ale Classification&quot;</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##               
## knn_model_Ales   0   1
##              0 201   1
##              1   2  77
##                                           
##                Accuracy : 0.9893          
##                  95% CI : (0.9691, 0.9978)
##     No Information Rate : 0.7224          
##     P-Value [Acc &gt; NIR] : &lt;2e-16          
##                                           
##                   Kappa : 0.9735          
##                                           
##  Mcnemar&#39;s Test P-Value : 1               
##                                           
##             Sensitivity : 0.9901          
##             Specificity : 0.9872          
##          Pos Pred Value : 0.9950          
##          Neg Pred Value : 0.9747          
##              Prevalence : 0.7224          
##          Detection Rate : 0.7153          
##    Detection Prevalence : 0.7189          
##       Balanced Accuracy : 0.9887          
##                                           
##        &#39;Positive&#39; Class : 0               
## </code></pre>
<p>This model is 98.93% accurate in predicting whether a beer is an IPA using ABV and IBU.We are 95% confident that the true accuracy is between 96.91% and 99.78%.</p>
<p>KNN classification of all other Ales. <img src="CaseStudy1_files/figure-html/KNN%20All%20Other%20Ales-1.png" width="672" /></p>
<pre><code>## [1] &quot;Confusion Matrix of Ale Classification&quot;</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##               
## knn_model_Ales   0   1
##              0 165   3
##              1   0 113
##                                           
##                Accuracy : 0.9893          
##                  95% CI : (0.9691, 0.9978)
##     No Information Rate : 0.5872          
##     P-Value [Acc &gt; NIR] : &lt;2e-16          
##                                           
##                   Kappa : 0.9779          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.2482          
##                                           
##             Sensitivity : 1.0000          
##             Specificity : 0.9741          
##          Pos Pred Value : 0.9821          
##          Neg Pred Value : 1.0000          
##              Prevalence : 0.5872          
##          Detection Rate : 0.5872          
##    Detection Prevalence : 0.5979          
##       Balanced Accuracy : 0.9871          
##                                           
##        &#39;Positive&#39; Class : 0               
## </code></pre>
<p>This model is 98.93% accurate in predicting whether a beer is an Ale other than IPA using ABV and IBU.We are 95% confident that the true accuracy is between 96.91% and 99.78%.</p>
<p>A basic Machine Learning pipeline is used for IBU predictions of the data with missing values for IBU.<br />
A “No Skill” prediction is leveraged as a baseline, then linear regression, random forest and XGBoost are tested. The accuracy on all test sets are then aggregated (via RMSE). <img src="CaseStudy1_files/figure-html/Machine%20Learning%20Pipeline-1.png" width="672" /></p>
<pre><code>## 
## Call:
## lm(formula = f, data = train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -49.418  -7.917  -1.180   6.201  73.415 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -15.007      2.496  -6.012 2.48e-09 ***
## ABV          706.349     41.354  17.080  &lt; 2e-16 ***
## IPA           13.029      5.235   2.489 0.012954 *  
## Stout          8.602      2.282   3.770 0.000172 ***
## APA           13.538      1.887   7.174 1.33e-12 ***
## Porter        -2.275      2.539  -0.896 0.370527    
## Lager         -2.044      1.895  -1.079 0.280976    
## Blonde        -5.788      2.401  -2.410 0.016094 *  
## RedAle         4.021      2.090   1.924 0.054607 .  
## BlackAle      24.580      3.553   6.919 7.68e-12 ***
## WheatAle      -5.170      2.446  -2.113 0.034813 *  
## American       6.657      1.439   4.626 4.17e-06 ***
## English        4.500      2.490   1.807 0.070997 .  
## top_states     0.584      2.061   0.283 0.776944    
## ABV:IPA      264.270     76.123   3.472 0.000537 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.58 on 1109 degrees of freedom
## Multiple R-squared:  0.7264, Adjusted R-squared:  0.723 
## F-statistic: 210.3 on 14 and 1109 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><img src="CaseStudy1_files/figure-html/Machine%20Learning%20Pipeline-2.png" width="672" /><img src="CaseStudy1_files/figure-html/Machine%20Learning%20Pipeline-3.png" width="672" /></p>
<pre><code>##    user  system elapsed 
##   36.47    1.96   38.61</code></pre>
<p><img src="CaseStudy1_files/figure-html/Machine%20Learning%20Pipeline-4.png" width="672" /></p>
<pre><code>## Bootstrap sampling is being applied, p=0.1 argument is ignored 
## running: regression cross-validation with 10 iterations 
## running iteration: 1 
## running iteration: 2 
## running iteration: 3 
## running iteration: 4 
## running iteration: 5 
## running iteration: 6 
## running iteration: 7 
## running iteration: 8 
## running iteration: 9 
## running iteration: 10</code></pre>
<pre><code>## Fit MSE = 187.1819 
## Fit percent variance explained = 72.3 
## Median permuted MSE = 5.389412 
## Median permuted percent variance explained = 99.205 
## Median cross-validation RMSE = 3.697813 
## Median cross-validation MBE = 0.2725954 
## Median cross-validation MAE = 2.066643 
## Range of ks p-values = 0.01652128 0.2699997 
## Range of ks D statistic = 0.05 0.07494145 
## RMSE cross-validation error variance = 0.3595239 
## MBE cross-validation error variance = 0.07097777 
## MAE cross-validation error variance = 0.05892349</code></pre>
<pre><code>## [18:12:13] INFO: amalgamation/../src/tree/updater_prune.cc:101: tree pruning end, 40 extra nodes, 0 pruned nodes, max_depth=8
## [1]  train-rmse:12.960311 
## [18:12:13] INFO: amalgamation/../src/tree/updater_prune.cc:101: tree pruning end, 502 extra nodes, 0 pruned nodes, max_depth=24
## [2]  train-rmse:10.572154</code></pre>
<p><img src="CaseStudy1_files/figure-html/Machine%20Learning%20Pipeline-5.png" width="672" /> The RMSE accuracy on the models are finalized.</p>
<pre><code>##    xg_rmse  rf_rmse  lm_rmse noskill_rmse
## 1 9.214933 9.197549 9.411602     21.93078</code></pre>
<p>The optimal model, random forest, is used to predict all NA’s in the original IBU data. <img src="CaseStudy1_files/figure-html/Predictions-1.png" width="672" /><img src="CaseStudy1_files/figure-html/Predictions-2.png" width="672" /> After performing an exploratory data analysis, interest regarding the missing IBU values led to a machine learning pipeline. While 3 models were tested, the random forest model is the most optimal. The model was used to estimate these missing values and were plotted along with the original data.</p>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
